spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/opsflow
    username: opsflow
    password: opsflow

  rabbitmq:
     host: localhost
     port: 5672
     username: guest
     password: guest


  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

  flyway:
    enabled: true
    baseline-on-migrate: true

  server:
    port: 8080