ALTER TABLE request
    ADD COLUMN IF NOT EXISTS creator VARCHAR(120),
    ADD COLUMN IF NOT EXISTS assignee VARCHAR(120),
    ADD COLUMN IF NOT EXISTS priority VARCHAR(30),
    ADD COLUMN IF NOT EXISTS type VARCHAR(50);

ALTER TABLE request
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;